# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'IndicatorsPage.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QSizePolicy, QVBoxLayout, QWidget)

from assets import IndicatorsPNG_rc

class Ui_IndicatorsPage(object):
    def setupUi(self, IndicatorsPage):
        if not IndicatorsPage.objectName():
            IndicatorsPage.setObjectName(u"IndicatorsPage")
        IndicatorsPage.resize(700, 650)
        IndicatorsPage.setMinimumSize(QSize(700, 650))
        IndicatorsPage.setStyleSheet(u"QFrame{background-color: qlineargradient(spread:pad, x1:0.477, y1:1, x2:0.488, y2:0, stop:0 rgba(27, 42, 45, 255), stop:0.741294 rgba(66, 78, 76, 255));\n"
"border-radius: 20px;\n"
"border: 0px, solid, black;\n"
"}")
        self.verticalLayout = QVBoxLayout(IndicatorsPage)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.widget = QWidget(IndicatorsPage)
        self.widget.setObjectName(u"widget")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QSize(600, 400))
        self.widget.setStyleSheet(u"")
        self.gridLayout = QGridLayout(self.widget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame_7 = QFrame(self.widget)
        self.frame_7.setObjectName(u"frame_7")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy1)
        self.frame_7.setMinimumSize(QSize(272, 272))
        self.frame_7.setMaximumSize(QSize(300, 16777215))
        self.frame_7.setStyleSheet(u"")
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.direction_label = QLabel(self.frame_7)
        self.direction_label.setObjectName(u"direction_label")
        self.direction_label.setGeometry(QRect(20, 8, 256, 256))
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(1)
        sizePolicy2.setHeightForWidth(self.direction_label.sizePolicy().hasHeightForWidth())
        self.direction_label.setSizePolicy(sizePolicy2)
        self.direction_label.setMinimumSize(QSize(256, 256))
        self.direction_label.setMaximumSize(QSize(16777215, 16777215))
        self.direction_label.setSizeIncrement(QSize(1, 1))
        self.direction_label.setMouseTracking(False)
        self.direction_label.setFrameShape(QFrame.Box)
        self.direction_label.setFrameShadow(QFrame.Plain)
        self.direction_label.setMidLineWidth(0)
        self.direction_label.setPixmap(QPixmap(u":/meters/Gyrometre.png"))
        self.direction_label.setScaledContents(True)
        self.direction_label.setAlignment(Qt.AlignCenter)
        self.direction_label.setIndent(-1)
        self.direction_needle = QLabel(self.frame_7)
        self.direction_needle.setObjectName(u"direction_needle")
        self.direction_needle.setGeometry(QRect(20, 8, 252, 252))
        self.direction_needle.setStyleSheet(u"background-color: transparent")
        self.direction_needle.setPixmap(QPixmap(u":/needles/Plane.png"))
        self.direction_needle.setScaledContents(False)
        self.direction_needle.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.frame_7, 1, 0, 1, 1)

        self.frame_4 = QFrame(self.widget)
        self.frame_4.setObjectName(u"frame_4")
        sizePolicy1.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy1)
        self.frame_4.setMinimumSize(QSize(272, 272))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.speed_label = QLabel(self.frame_4)
        self.speed_label.setObjectName(u"speed_label")
        self.speed_label.setGeometry(QRect(20, 8, 256, 256))
        sizePolicy2.setHeightForWidth(self.speed_label.sizePolicy().hasHeightForWidth())
        self.speed_label.setSizePolicy(sizePolicy2)
        self.speed_label.setMinimumSize(QSize(256, 256))
        self.speed_label.setMaximumSize(QSize(16777215, 16777215))
        self.speed_label.setSizeIncrement(QSize(1, 1))
        self.speed_label.setMouseTracking(False)
        self.speed_label.setFrameShape(QFrame.Box)
        self.speed_label.setFrameShadow(QFrame.Plain)
        self.speed_label.setMidLineWidth(0)
        self.speed_label.setPixmap(QPixmap(u":/meters/Speedometer.png"))
        self.speed_label.setScaledContents(True)
        self.speed_label.setAlignment(Qt.AlignCenter)
        self.speed_label.setIndent(-1)
        self.speed_needle = QLabel(self.frame_4)
        self.speed_needle.setObjectName(u"speed_needle")
        self.speed_needle.setGeometry(QRect(20, 8, 256, 256))
        self.speed_needle.setStyleSheet(u"background-color: transparent")
        self.speed_needle.setPixmap(QPixmap(u":/needles/needle.png"))
        self.speed_needle.setScaledContents(False)
        self.speed_needle.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.frame_4, 0, 0, 1, 1)

        self.frame_8 = QFrame(self.widget)
        self.frame_8.setObjectName(u"frame_8")
        sizePolicy1.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy1)
        self.frame_8.setMinimumSize(QSize(272, 272))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.vspeed_label = QLabel(self.frame_8)
        self.vspeed_label.setObjectName(u"vspeed_label")
        self.vspeed_label.setGeometry(QRect(20, 8, 256, 256))
        sizePolicy2.setHeightForWidth(self.vspeed_label.sizePolicy().hasHeightForWidth())
        self.vspeed_label.setSizePolicy(sizePolicy2)
        self.vspeed_label.setMinimumSize(QSize(256, 256))
        self.vspeed_label.setMaximumSize(QSize(16777215, 16777215))
        self.vspeed_label.setSizeIncrement(QSize(1, 1))
        self.vspeed_label.setMouseTracking(False)
        self.vspeed_label.setFrameShape(QFrame.Box)
        self.vspeed_label.setFrameShadow(QFrame.Plain)
        self.vspeed_label.setMidLineWidth(0)
        self.vspeed_label.setPixmap(QPixmap(u":/meters/Vertical_Speed.png"))
        self.vspeed_label.setScaledContents(True)
        self.vspeed_label.setAlignment(Qt.AlignCenter)
        self.vspeed_label.setIndent(-1)
        self.vspeed_needle = QLabel(self.frame_8)
        self.vspeed_needle.setObjectName(u"vspeed_needle")
        self.vspeed_needle.setGeometry(QRect(20, 8, 256, 256))
        self.vspeed_needle.setStyleSheet(u"background-color: transparent")
        self.vspeed_needle.setPixmap(QPixmap(u":/needles/needle.png"))
        self.vspeed_needle.setScaledContents(False)
        self.vspeed_needle.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.frame_8, 1, 1, 1, 1)

        self.frame_5 = QFrame(self.widget)
        self.frame_5.setObjectName(u"frame_5")
        sizePolicy1.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy1)
        self.frame_5.setMinimumSize(QSize(272, 272))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.gyro_label = QLabel(self.frame_5)
        self.gyro_label.setObjectName(u"gyro_label")
        self.gyro_label.setGeometry(QRect(20, 8, 256, 256))
        sizePolicy.setHeightForWidth(self.gyro_label.sizePolicy().hasHeightForWidth())
        self.gyro_label.setSizePolicy(sizePolicy)
        self.gyro_label.setMinimumSize(QSize(256, 256))
        self.gyro_label.setMaximumSize(QSize(16777215, 16777215))
        self.gyro_label.setStyleSheet(u"")
        self.gyro_label.setFrameShape(QFrame.NoFrame)
        self.gyro_label.setPixmap(QPixmap(u":/meters/Gyroscope.png"))
        self.gyro_label.setScaledContents(True)
        self.gyro_label.setAlignment(Qt.AlignCenter)
        self.gyro_label.setWordWrap(False)
        self.gyro_label.setOpenExternalLinks(False)
        self.gyro_needle = QLabel(self.frame_5)
        self.gyro_needle.setObjectName(u"gyro_needle")
        self.gyro_needle.setGeometry(QRect(20, 8, 256, 256))
        self.gyro_needle.setStyleSheet(u"background-color: transparent")
        self.gyro_needle.setPixmap(QPixmap(u":/needles/Needle_gs.png"))
        self.gyro_needle.setScaledContents(False)
        self.gyro_needle.setAlignment(Qt.AlignCenter)
        self.gyro_needle.setWordWrap(False)
        self.gyro_needle.setMargin(0)

        self.gridLayout.addWidget(self.frame_5, 0, 1, 1, 1)

        self.Altitude = QFrame(self.widget)
        self.Altitude.setObjectName(u"Altitude")
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.Altitude.sizePolicy().hasHeightForWidth())
        self.Altitude.setSizePolicy(sizePolicy3)
        self.Altitude.setMinimumSize(QSize(60, 0))
        self.Altitude.setFrameShape(QFrame.StyledPanel)
        self.Altitude.setFrameShadow(QFrame.Raised)
        self.altitude_label = QLabel(self.Altitude)
        self.altitude_label.setObjectName(u"altitude_label")
        self.altitude_label.setGeometry(QRect(5, 24, 50, 501))
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.altitude_label.sizePolicy().hasHeightForWidth())
        self.altitude_label.setSizePolicy(sizePolicy4)
        self.altitude_label.setMinimumSize(QSize(50, 400))
        self.altitude_label.setMaximumSize(QSize(16777215, 512))
        self.altitude_label.setPixmap(QPixmap(u":/meters/Altitude.png"))
        self.altitude_label.setScaledContents(True)
        self.altitude_needle = QLabel(self.Altitude)
        self.altitude_needle.setObjectName(u"altitude_needle")
        self.altitude_needle.setGeometry(QRect(0, 508, 60, 20))
        self.altitude_needle.setStyleSheet(u"background-color: transparent")
        self.altitude_needle.setPixmap(QPixmap(u":/needles/Rectangle.png"))
        self.altitude_needle.setScaledContents(True)

        self.gridLayout.addWidget(self.Altitude, 0, 2, 2, 1)


        self.verticalLayout.addWidget(self.widget)

        self.widget_2 = QWidget(IndicatorsPage)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setMinimumSize(QSize(0, 60))
        self.horizontalLayout = QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.xpos = QFrame(self.widget_2)
        self.xpos.setObjectName(u"xpos")
        self.xpos.setMinimumSize(QSize(0, 0))
        self.xpos.setFrameShape(QFrame.StyledPanel)
        self.xpos.setFrameShadow(QFrame.Raised)
        self.xpos_label = QLabel(self.xpos)
        self.xpos_label.setObjectName(u"xpos_label")
        self.xpos_label.setGeometry(QRect(10, 10, 81, 16))

        self.horizontalLayout.addWidget(self.xpos)

        self.ypos = QFrame(self.widget_2)
        self.ypos.setObjectName(u"ypos")
        self.ypos.setFrameShape(QFrame.StyledPanel)
        self.ypos.setFrameShadow(QFrame.Raised)
        self.ypos_label = QLabel(self.ypos)
        self.ypos_label.setObjectName(u"ypos_label")
        self.ypos_label.setGeometry(QRect(10, 10, 81, 16))

        self.horizontalLayout.addWidget(self.ypos)

        self.battery = QFrame(self.widget_2)
        self.battery.setObjectName(u"battery")
        self.battery.setFrameShape(QFrame.StyledPanel)
        self.battery.setFrameShadow(QFrame.Raised)
        self.battery_label = QLabel(self.battery)
        self.battery_label.setObjectName(u"battery_label")
        self.battery_label.setGeometry(QRect(10, 10, 51, 16))

        self.horizontalLayout.addWidget(self.battery)

        self.flightmode = QFrame(self.widget_2)
        self.flightmode.setObjectName(u"flightmode")
        self.flightmode.setMinimumSize(QSize(225, 0))
        self.flightmode.setFrameShape(QFrame.StyledPanel)
        self.flightmode.setFrameShadow(QFrame.Raised)
        self.flightmode_label = QLabel(self.flightmode)
        self.flightmode_label.setObjectName(u"flightmode_label")
        self.flightmode_label.setGeometry(QRect(10, 10, 161, 16))

        self.horizontalLayout.addWidget(self.flightmode)


        self.verticalLayout.addWidget(self.widget_2)


        self.retranslateUi(IndicatorsPage)

        QMetaObject.connectSlotsByName(IndicatorsPage)
    # setupUi

    def retranslateUi(self, IndicatorsPage):
        IndicatorsPage.setWindowTitle(QCoreApplication.translate("IndicatorsPage", u"Form", None))
        self.direction_label.setText("")
        self.direction_needle.setText("")
        self.speed_label.setText("")
        self.speed_needle.setText("")
        self.vspeed_label.setText("")
        self.vspeed_needle.setText("")
        self.gyro_label.setText("")
        self.gyro_needle.setText("")
        self.altitude_label.setText("")
        self.altitude_needle.setText("")
        self.xpos_label.setText(QCoreApplication.translate("IndicatorsPage", u"X:", None))
        self.ypos_label.setText(QCoreApplication.translate("IndicatorsPage", u"Y:", None))
        self.battery_label.setText(QCoreApplication.translate("IndicatorsPage", u"Battery:", None))
        self.flightmode_label.setText(QCoreApplication.translate("IndicatorsPage", u"FlightMode:", None))
    # retranslateUi

